CREATE DATABASE LIBRARYMANAGEMENT;
USE LIBRARYMANAGEMENT;
 
CREATE TABLE BOOKS(
	BOOKID INT PRIMARY KEY IDENTITY,
	TITLE VARCHAR(20) NOT NULL,
	AUTHOR VARCHAR(20),
	QUANTITY INT);

CREATE TABLE MEMBERS(
	MEMBERID INT PRIMARY KEY IDENTITY,
	MEMBERNAME VARCHAR(20));

CREATE TABLE TRANSACTIONS(
	ID INT PRIMARY KEY IDENTITY,
	BOOKID INT REFERENCES BOOKS(BOOKID),
	MEMBERID INT REFERENCES MEMBERS(MEMBERID),
	DATE DATETIME DEFAULT GETDATE()
	);

drop table TRANSACTIONS

exec sp_rename 'BOOKS.QUNTITY' ,'QUANTITY','column'

select * from BOOKS
select * from MEMBERS;
SELECT * FROM TRANSACTIONS









 
